### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by glimchb**
@mraineri please review

### CODE REVIEW

**Comment by MoshiBin** [comment]
LGTM 👍

**Comment by mraineri** [comment]
It might be worth adding some documentation in the readme to how to use this with respect to a given mockup. Otherwise it looks good though.

**Comment by glimchb** [comment]
> It might be worth adding some documentation in the readme to how to use this with respect to a given mockup. Otherwise it looks good though.

added readme section

**Comment by mraineri** [comment]
I think what you just pushed is a good start; I'll see if there's more language I can put in around it. I haven't really used Docker before, but having the raw commands like that gives me enough to fill in more.

**Comment by mraineri** [comment]
Approved 10/16

**Pull request merged**
