### PR TITLE
Mock simple actions

### PR DESCRIPTION
**Pull request by mcalmer**
Mock Power Management Actions PowerOn, PowerOff and Reboot

### CODE REVIEW

**Comment by mraineri** [comment]
@mcalmer the group is wondering if this type of functionality is starting to cross the line into what we think belongs in he Redfish Interface Emulator (https://github.com/DMTF/Redfish-Interface-Emulator). Usually we try to limit the operations on the mockup server to GETs (and some support for POST just to make generic clients pass certain checks).

**Comment by jcleung5549** [comment]
In the Redfish Interface Emulator repository, look in ./api_emulator/redfish/ComputerSystem, you will find the files

- ResetAction_api.py
- ResetActionInfo_api.py
- ResetActionInfo_template.py

The first file purpose is to emulate the POST to ResetAction.  Currently, it is a stuff and your code could replace that stub.

**Comment by mcalmer** [comment]
Thanks for the pointer. I was not aware that there is a second emulator. I will have a look what we can do with it.

**Comment by mraineri** [comment]
Closing; if the Redfish Interface Emulator is not sufficient and this needs to be part of the Redfish Mockup Server, please let us know and we can revisit this topic.

**Pull request closed without merging**
