### PR TITLE
SSDP server interface binding fixes

### LINKED ISSUE #94: SSDP does not work
I have a local instance of the Redfish Mockup Server. I am running it on Windows 11, my firewall is disabled and I tried it with the Windows' SSDP Service on and off.

This is my client code:

``` C#
// file Program.cs

using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorPages();
builder.Services.AddHostedService<RedfishServerDiscoveryService>();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseStaticFiles();
app.UseRouting();
app.MapRazorPages();
app.Run();

public class RedfishServerDiscoveryService : BackgroundService
{
    private readonly ILogger<RedfishServerDiscoveryService> _logger;

    public RedfishServerDiscoveryService(ILogger<RedfishServerDiscoveryService> logger)
    {
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        // Send an SSDP search message to the network to discover Redfish servers
        var ssdpMessage = "M-SEARCH * HTTP/1.1\r\n" +
                          "HOST: 239.255.255.250:1900\r\n" +
                          "MAN: \"ssdp:discover\"\r\n" +
                          "ST: urn:dmtf-org:service:redfish-rest:1\r\n" +
                          "MX: 5\r\n" +
                          "\r\n";
        var ssdpBytes = Encoding.UTF8.GetBytes(ssdpMessage);
        var ssdpEndpoint = new IPEndPoint(IPAddress.Parse("239.255.255.250"), 1900);

        using (var udpClient = new UdpClient())
        {
            udpClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
            udpClient.JoinMulticastGroup(IPAddress.Parse("239.255.255.250"));

            while (!stoppingToken.IsCancellationRequested)
            {
                try
                {
                    await udpClient.SendAsync(ssdpBytes, ssdpBytes.Length, ssdpEndpoint);
                    _logger.LogInformation("Sent SSDP search message to discover Redfish servers.");

                    var receiveTask = udpClient.ReceiveAsync();
                    if (await Task.WhenAny(receiveTask, Task.Delay(TimeSpan.FromSeconds(10))) == receiveTask)
                    {
                        var response = receiveTask.Result;
                        var responseMessage = Encoding.UTF8.GetString(response.Buffer);
                        _logger.LogInformation($"Received SSDP response from {response.RemoteEndPoint}: {responseMessage}");
                    }
                    else
                    {
                        _logger.LogInformation("No SSDP response received from Redfish servers.");
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error discovering Redfish servers using SSDP.");
                }
            }
        }
    }
}

```

expected behavior: The Mockup Server should respond to the SSDP messages
actual behavior: The Mockup Server does not respond the messages

### PR DESCRIPTION
**Pull request by mraineri**
Fix #94 (pending confirmation)

Made changes to bind to all interfaces, as well as enable listening on the loopback address.

@andremarcondesteixeira would you be able to test this out on your system with your SSDP client code? The changes work for me with other SSDP utilities, and I was able to reproduce your issue with the rf_discover.py tool:

```
C:\Users\rainem1>rf_discover.py
Redfish services:
92384634-2938-2342-8820-489239905423: http://127.0.0.1:8000/redfish/v1
```

### CODE REVIEW

**Comment by mraineri** [comment]
5/12: Will hold off on merging until the submitter verifies the fix before merging

**Comment by andremarcondesteixeira** [comment]
Cool, I'll check it out and let you know

**Comment by andremarcondesteixeira** [comment]
It works!

**Comment by mraineri** [comment]
Awesome, glad to hear! Merging now and making a new release...

**Pull request merged**
