### PR TITLE
Update RfSSDPServer

### PR DESCRIPTION
**Pull request by rite2hhh**
* Fix a typo 
  SSDP was misspelled as SDDP

* Add some comments and documentation
   around the requirement to create and join
   a multicast group

### CODE REVIEW

**Comment by rite2hhh** [comment]
I'm new to contributing, I did not see any `CONTRIBUTING` file that indicates the steps for this repo...

**Comment by mraineri** [comment]
@rite2hhh We don't exactly have a formal process; if you want to make a contribution, simply make a pull request and the DMTF will review the changes.

I see you have this set to a draft; do you have further changes to make?

**Comment by rite2hhh** [comment]
@mraineri, no further changes for this pull request. I opened it as a draft to confirm if I needed to do something more before I created a pull request.

**Comment by mraineri** [comment]
Approved 3/19

**Pull request merged**
