### PR TITLE
clean_path takes two arguments

### PR DESCRIPTION
**Pull request by robisonjoel**
Calling DELETE would cause a traceback.

### CODE REVIEW

**Comment by tomasg2012** [comment]
The correct way to fix this would be to make that clean_path call similar to the other calls (using self.shortForm), otherwise it will likely fail when using the -S command.

**Comment by robisonjoel** [comment]
> The correct way to fix this would be to make that clean_path call similar to the other calls (using self.shortForm), otherwise it will likely fail when using the -S command.

Right you are!  honestly not sure how I missed that :/

**Comment by tomasg2012** [comment]
I missed it first!  The function also doesn't detail what that parameter is for, it should be optional.

**Comment by mraineri** [comment]
Approved 10/25

**Pull request merged**
